name: logic_mathematics
description: "An application for learning and practicing mathematical logic. Includes lessons, exercises, and quizzes to enhance understanding of logical concepts."

version: 2.3.2+36

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl:
  cupertino_icons: ^1.0.8
  shared_preferences: 
  package_info_plus:
  get_it:
  fluttertoast:
  math_expressions:
  internet_connection_checker_plus: 
  new_version_plus: ^0.1.2
  uuid: ^4.5.1
  responsive_sizer:
  flutter_easyloading:
  google_fonts: ^6.3.3
  flutter_spinkit: ^5.2.1
  url_launcher:
  flutter_secure_storage: ^9.2.4
  flutter_svg: 
  google_mobile_ads:
  flutter_confetti: ^0.5.1
  dio: ^5.8.0+1
  in_app_review: ^2.0.11
  flutter_widget_from_html:
  device_info_plus:
  share_plus: ^12.0.0
  in_app_purchase: 
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_riverpod: ^3.0.3
   # Generate Unique Id
  # Easily detect Swipes
  flutter_swipe_detector: ^2.0.0
  shorebird_code_push:
  bonfire: ^3.13.0
  flame_audio: ^2.11.12
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  firebase_analytics: ^12.0.4
  #webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  permission_handler: ^12.0.1
  # firebase_remote_config: ^6.1.3
  # flutter_gemma: 
  # Thư viện AI local Gemma (Google)
  #flutter_markdown: ^0.7.1
  #shorebird release android --app-id=app.ozilogic.math --version=1.0.5+11
  image_picker:
  oziapi :
    path: ./packages/oziapi/
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  build_runner:
  flutter_gen_runner:
  flutter_native_splash: 
  change_app_package_name: ^1.5.0 
  # intl_utils: ^2.8.11

flutter_gen:
  output: lib/gen/ 

  integrations:
    image: true
    flutter_svg: true
  
  assets:
    enabled: true
    outputs:
      class_name: AssetsImages
      package_parameter_enabled: false
  #dart run build_runner build 

flutter_native_splash: # this command dart run flutter_native_splash:create

  android_12:
    color: "#FFFFFF"
  android: true
  ios: true
  web: false
  fullscreen: true
  background_image: assets/images/image_bg_splash.png

flutter:

  uses-material-design: true
  generate: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/web_duck_war/
    - assets/circuit_connect/
    - assets/quantum_link/
    - assets/pack_pal/
    - assets/sortie/
    - assets/wood_block_puzzle/
    - assets/evolution_merge/
    - assets/liquid_sort/
    - assets/cozy_tiles/
    - assets/garden_gulp/
    - shorebird.yaml

targets:
  $default:
    sources:
      include:
        - pubspec.yaml


#ID Admod App ca-app-pub-8031150677135815~4943302819
#ID Admod Banner ca-app-pub-8031150677135815/3231600048
#ID Admod Inter ca-app-pub-8031150677135815/4213509223
#ID Admod OpenApp ca-app-pub-8031150677135815/3520928322
#ID Admod Native ca-app-pub-8031150677135815/1431918935